name: Create a release

env:
  PYTHON_VERSION: "3.10"

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"

jobs:
  cancel-previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  check:
    name: Detect version change
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect new version
        if: ${{ github.event_name == 'push' }}
        run: |
          NEW_VERSION="$(./versionChangeCheck.sh)"
          echo "New version if changed = '$NEW_VERSION'"
          echo "newVersion=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Detect new version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "New version if changed = '${{ github.event.inputs.version }}'"
          echo "newVersion=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: ["check"]

    if: ${{ (needs.check.outputs.newVersion != '') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install rye
        run: |
          curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Build
        run: rye build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ needs.check.outputs.newVersion }}
          files: dist/**

      - run: rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
